

__default__:
    queue: "mem.q"
    nCPUs: "4"
    memory: "4000"
#    resources: "\"select[mem>20000] rusage[mem=20000] span[hosts=1]\""
    name: "JOBNAME.{rule}.{wildcards}"
    output: "logs/cluster/{rule}.{wildcards}.out",
    error: "logs/cluster/{rule}.{wildcards}.err"

"trimming_PE" :
    memory: 30000,
    resources: "\"select[mem>30000] rusage[mem=30000] span[hosts=1]\""

