outputdir: 21Anopheles_dataset
species_tree: data/INPUT_DATA/Anopheles_species_tree_X_topology.nwk
families: data/INPUT_DATA/gene_families.txt
GFF_dir: data/INPUT_DATA/GFF
ASSEMBLY_dir: data/INPUT_DATA/FASTA/SCAFF
gene_trees: data/GENE_TREES/trees_DeCoSTAR_Xtopo.nwk
BESST_dir: data/DATA_SEQ/SCAFFOLDING/BESST-2.2.6/Bowtie2_k100/TRIM
decostar_gene_trees: DeCoSTAR_Anopheles_Xtopo_gene_trees
SEP: '@'
config_decostar: config_files/decostar/DeCoSTAR_21Anopheles_Xtopo.param.txt
outputdir_decostar: results/decostar/Xtopo/ADseq+scaff_Boltz_kT0.1
prefix_decostar: DeCoSTAR_21Anopheles_Xtopo_ADseq+scaff_Boltz_kT0.1
linearization_threshold: "0.1"
