outputdir: 27avian_dataset
species_tree: data/INPUT_DATA/27avian_species_tree.nwk
families: data/INPUT_DATA/27avian_trees.nwk
chromosome_file: data/INPUT_DATA/27avian_species.txt
GFF_dir: data/INPUT_DATA/GFF
ASSEMBLY_dir: data/INPUT_DATA/FASTA/SCAFF
gene_trees: data/GENE_TREES/unrooted_trees_filtered.nwk
BESST_dir: data/DATA_SEQ/SCAFFOLDING/BESST-2.2.6/Bowtie2_k100/TRIM
decostar_gene_trees: DeCoSTAR_27avian_gene_trees
SEP: \|
config_decostar: config_files/decostar/DeCoSTAR_27avian.param.txt
outputdir_decostar: results/decostar/ADseq+scaff_Boltz_kT0.1
prefix_decostar: DeCoSTAR_27avian_ADseq+scaff_Boltz_kT0.1
linearization_threshold: "0.1"
linearization_algo: M2
AGP_dir: data/INPUT_DATA/chromosome_map
